name: Battle Cats Clone

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libsdl2-dev sdl_ttf

    - name: Compile the project
      run: |
        make
